<?php
declare(strict_types=1);

// PublicApisDatabase SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

PublicApisDatabaseUtility::setRegistrar(function (PublicApisDatabaseUtility $u): void {
    $u->clean = [PublicApisDatabaseClean::class, 'call'];
    $u->done = [PublicApisDatabaseDone::class, 'call'];
    $u->make_error = [PublicApisDatabaseMakeError::class, 'call'];
    $u->feature_add = [PublicApisDatabaseFeatureAdd::class, 'call'];
    $u->feature_hook = [PublicApisDatabaseFeatureHook::class, 'call'];
    $u->feature_init = [PublicApisDatabaseFeatureInit::class, 'call'];
    $u->fetcher = [PublicApisDatabaseFetcher::class, 'call'];
    $u->make_fetch_def = [PublicApisDatabaseMakeFetchDef::class, 'call'];
    $u->make_context = [PublicApisDatabaseMakeContext::class, 'call'];
    $u->make_options = [PublicApisDatabaseMakeOptions::class, 'call'];
    $u->make_request = [PublicApisDatabaseMakeRequest::class, 'call'];
    $u->make_response = [PublicApisDatabaseMakeResponse::class, 'call'];
    $u->make_result = [PublicApisDatabaseMakeResult::class, 'call'];
    $u->make_point = [PublicApisDatabaseMakePoint::class, 'call'];
    $u->make_spec = [PublicApisDatabaseMakeSpec::class, 'call'];
    $u->make_url = [PublicApisDatabaseMakeUrl::class, 'call'];
    $u->param = [PublicApisDatabaseParam::class, 'call'];
    $u->prepare_auth = [PublicApisDatabasePrepareAuth::class, 'call'];
    $u->prepare_body = [PublicApisDatabasePrepareBody::class, 'call'];
    $u->prepare_headers = [PublicApisDatabasePrepareHeaders::class, 'call'];
    $u->prepare_method = [PublicApisDatabasePrepareMethod::class, 'call'];
    $u->prepare_params = [PublicApisDatabasePrepareParams::class, 'call'];
    $u->prepare_path = [PublicApisDatabasePreparePath::class, 'call'];
    $u->prepare_query = [PublicApisDatabasePrepareQuery::class, 'call'];
    $u->graphql_body = [PublicApisDatabaseGraphql::class, 'body'];
    $u->graphql_errors = [PublicApisDatabaseGraphql::class, 'errors'];
    $u->result_basic = [PublicApisDatabaseResultBasic::class, 'call'];
    $u->result_body = [PublicApisDatabaseResultBody::class, 'call'];
    $u->result_headers = [PublicApisDatabaseResultHeaders::class, 'call'];
    $u->transform_request = [PublicApisDatabaseTransformRequest::class, 'call'];
    $u->transform_response = [PublicApisDatabaseTransformResponse::class, 'call'];
});
